"""Central configuration for the DAS732 A1 pipeline.

Every narrative/parametric choice that spans multiple scripts lives here so
the report, figures, and tests cannot drift apart:

  - era binning (used by preprocessing and every temporal figure)
  - colour palettes (used by both figure scripts)
  - the link-hosting classifier (used by preprocessing)
  - k-means selection parameters (used by Figure 13 and src/06_k_selection.py;
    the Appendix C table is regenerated by that script)

Deliberately NOT centralised: per-figure label lists and annotation offsets
(presentation choices of individual figures), and figure file naming.
"""
import pandas as pd

# ---------------------------------------------------------------- clustering
RANDOM_STATE = 0
N_INIT = 10
K_RANGE = range(2, 9)           # k values assessed (report Appendix C)
MIN_PROFILE_SIZE = 6            # a profile must contain >= 6 of the 50 communities...
MAX_SMALL_PROFILES = 1          # ...unless it is the single structural outlier (AskReddit)
STABILITY_SEEDS = range(20)     # seed 0 = reference; ARI averaged over the other 19

# ---------------------------------------------------------------------- eras
ERA_BINS = [2010, 2015, 2017, 2019, 2021, 2024]
ERA_LABELS = ["<=2015", "2016-17", "2018-19", "2020-21", "2022-24"]

# ------------------------------------------------------------------- colours
# Okabe-Ito colourblind-safe palette
OI = {"blue": "#0072B2", "orange": "#E69F00", "green": "#009E73",
      "verm": "#D55E00", "purple": "#CC79A7", "sky": "#56B4E9",
      "grey": "#7F7F7F"}
PT_COLORS = {"image": OI["blue"], "link": OI["orange"],
             "text": OI["green"], "video": OI["verm"]}
ERA_COLORS = {"<=2015": OI["sky"], "2016-17": OI["green"],
              "2018-19": OI["blue"], "2020-21": OI["orange"],
              "2022-24": OI["verm"]}

VIDEO_HOST_FRAGMENTS = ("gfycat", "streamable", "vimeo", "twitch")


def classify_domain(d):
    """Coarse hosting classifier for the platform-migration story."""
    if pd.isna(d):
        return "no link"
    d = d.lower()
    if d.startswith("self."):
        return "self post"
    if "redd.it" in d:
        return "reddit-native"
    if "imgur" in d:
        return "imgur"
    if "youtu" in d:
        return "youtube"
    if any(h in d for h in VIDEO_HOST_FRAGMENTS):
        return "other video hosts"
    return "other external"
